# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TSP
                                 A QGIS plugin
 用于解决旅行商问题
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-11
        copyright            : (C) 2025 by SYT
        email                : 2982893682@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TSP class from file TSP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TSP import TSP
    return TSP(iface)
