# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TSP_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TSPDialogBase(object):
    def setupUi(self, TSPDialogBase):
        TSPDialogBase.setObjectName("TSPDialogBase")
        TSPDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(TSPDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(TSPDialogBase)
        self.button_box.accepted.connect(TSPDialogBase.accept)
        self.button_box.rejected.connect(TSPDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(TSPDialogBase)

    def retranslateUi(self, TSPDialogBase):
        _translate = QtCore.QCoreApplication.translate
        TSPDialogBase.setWindowTitle(_translate("TSPDialogBase", "TSP"))
