# -*- coding: utf-8 -*-
"""
/***************************************************************************
 tsp
                                 A QGIS plugin
 tsp
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-18
        copyright            : (C) 2024 by jie
        email                : 2057116416@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load tsp class from file tsp.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tsp import tsp
    return tsp(iface)
