# -*- coding: utf-8 -*-
"""
/***************************************************************************
 tspDialog
                                 A QGIS plugin
 tsp
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-18
        git sha              : $Format:%H$
        copyright            : (C) 2024 by jie
        email                : 2057116416@qq.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5.QtWidgets import QFileDialog
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis._core import QgsMapLayerProxyModel

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'tsp_dialog_base.ui'))


class tspDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(tspDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        # 设置过滤器
        self.RoadmMapLayerComboBox.setFilters(QgsMapLayerProxyModel.LineLayer)
        self.PointmMapLayerComboBox.setFilters(QgsMapLayerProxyModel.PointLayer)

        self.pushButtonInputOutput.clicked.connect(self.browse)

    def browse(self):
        """Opens a window to set the location of the output file."""
        fileName0 = QFileDialog.getSaveFileName(self, 'Save as', 'F:/Desktop',
                                                "Shapefile (*.shp);;All files (*)")
        fileName = fileName0[0]
        self.lineEditOutput.setText(fileName)

