# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tsp_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tspDialogBase(object):
    def setupUi(self, tspDialogBase):
        tspDialogBase.setObjectName("tspDialogBase")
        tspDialogBase.resize(684, 422)
        self.button_box = QtWidgets.QDialogButtonBox(tspDialogBase)
        self.button_box.setGeometry(QtCore.QRect(80, 350, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.textBrowserDescription = QtWidgets.QTextBrowser(tspDialogBase)
        self.textBrowserDescription.setGeometry(QtCore.QRect(450, 20, 211, 371))
        self.textBrowserDescription.setObjectName("textBrowserDescription")
        self.tabWidget = QtWidgets.QTabWidget(tspDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 401, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.labelInputPoint = QtWidgets.QLabel(self.tab)
        self.labelInputPoint.setGeometry(QtCore.QRect(30, 100, 120, 20))
        self.labelInputPoint.setObjectName("labelInputPoint")
        self.PointmMapLayerComboBox = QgsMapLayerComboBox(self.tab)
        self.PointmMapLayerComboBox.setGeometry(QtCore.QRect(30, 140, 300, 30))
        self.PointmMapLayerComboBox.setObjectName("PointmMapLayerComboBox")
        self.pushButtonInputRoad = QtWidgets.QPushButton(self.tab)
        self.pushButtonInputRoad.setGeometry(QtCore.QRect(340, 50, 40, 30))
        self.pushButtonInputRoad.setObjectName("pushButtonInputRoad")
        self.pushButtonInputPoint = QtWidgets.QPushButton(self.tab)
        self.pushButtonInputPoint.setGeometry(QtCore.QRect(340, 140, 40, 30))
        self.pushButtonInputPoint.setObjectName("pushButtonInputPoint")
        self.labelInputRoad = QtWidgets.QLabel(self.tab)
        self.labelInputRoad.setGeometry(QtCore.QRect(30, 20, 100, 20))
        self.labelInputRoad.setObjectName("labelInputRoad")
        self.RoadmMapLayerComboBox = QgsMapLayerComboBox(self.tab)
        self.RoadmMapLayerComboBox.setGeometry(QtCore.QRect(30, 50, 300, 30))
        self.RoadmMapLayerComboBox.setObjectName("RoadmMapLayerComboBox")
        self.pushButtonInputOutput = QtWidgets.QPushButton(self.tab)
        self.pushButtonInputOutput.setGeometry(QtCore.QRect(340, 230, 40, 30))
        self.pushButtonInputOutput.setObjectName("pushButtonInputOutput")
        self.labelInputOutput = QtWidgets.QLabel(self.tab)
        self.labelInputOutput.setGeometry(QtCore.QRect(30, 190, 120, 20))
        self.labelInputOutput.setObjectName("labelInputOutput")
        self.lineEditOutput = QtWidgets.QLineEdit(self.tab)
        self.lineEditOutput.setGeometry(QtCore.QRect(30, 230, 300, 30))
        self.lineEditOutput.setObjectName("lineEditOutput")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(-13, -9, 421, 231))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(tspDialogBase)
        self.tabWidget.setCurrentIndex(0)
        self.button_box.accepted.connect(tspDialogBase.accept)
        self.button_box.rejected.connect(tspDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(tspDialogBase)

    def retranslateUi(self, tspDialogBase):
        _translate = QtCore.QCoreApplication.translate
        tspDialogBase.setWindowTitle(_translate("tspDialogBase", "tsp"))
        self.textBrowserDescription.setHtml(_translate("tspDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:14pt;\">TSP算法</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt;\">该插件的开发是用于解决</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt;\">TSP问题，输入参数有两</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt;\">个，第一个参数为路网数</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt;\">据，第二个参数为目标点</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt;\">数据，程序运行后，将把</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt;\">路网上的最优路径可视化</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt;\">显示在屏幕上，按路径颜</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt;\">色由深到浅/目标点大小</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt;\">由小到大可以判断路径的</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt;\">先后顺序。</span></p></body></html>"))
        self.labelInputPoint.setText(_translate("tspDialogBase", "输入目的点数据："))
        self.pushButtonInputRoad.setText(_translate("tspDialogBase", "..."))
        self.pushButtonInputPoint.setText(_translate("tspDialogBase", "..."))
        self.labelInputRoad.setText(_translate("tspDialogBase", "输入路网数据："))
        self.pushButtonInputOutput.setText(_translate("tspDialogBase", "..."))
        self.labelInputOutput.setText(_translate("tspDialogBase", "输入目的点数据："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("tspDialogBase", "参数"))
        self.textBrowser.setHtml(_translate("tspDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt;\">  别看了，啥都没有</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("tspDialogBase", "记录"))
from qgsmaplayercombobox import QgsMapLayerComboBox
